name: Pre-Release

on:
  push:
    branches: ['vial']

jobs:

  build-ergohaven:
    uses: ./.github/workflows/build-ergohaven.yml

  pre-release:
    name: Pre-Release
    needs:
      - build-ergohaven
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      pull-requests: 'read'

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: ergohaven_fw

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: 'Latest Build'
          files: |
            ergohaven_fw/**/*.uf2
